---
title: "Lab 8: Simple Loops"
subtitle: "Stat 133, Fall 2018"
author: "Nabeil Kizilbash"
output: 
fontsize: 11pt
urlcolor: blue
---


# For Loops 

```{r}
vec <- c(3, 1, 4) 
vec + 1
```



```{r eval = FALSE}
vec[1] + 1
vec[2] + 1
vec[3] + 1
```


```{r}
vec <- c(3, 1, 4) # Change this value!

for (j in c(3,1,4)) { # Replace c() with an appropriate sequence.
  # Fill in.
  
  3*j
  print(3*j)
  
  
}
```



What if you want to create a vector `vec2`, in which you store the values 
produced at each iteration of the loop? Here's one possibility:

```{r}
vec <- c(3, 1, 4)  # Change this value!
vec2 <- rep(0, length(vec))  # "empty" of zeros vector to be filled in the loop
for (i in vec) {# Replace c() with an appropriate sequence.
  # Fill in.
  
  vec2[i] = i*3
  
  
}

vec2
```







## Summation Series

```{r}

n<- 20

vec <- rep(1, n)


for (i in vec[-1] ){
  
  vec[i] = vec[i]/(2**i)
  print(vec[i])
  
  
}


#Yes the series converges to zero



for (i in vec[-1]){
  
  vec[i] = vec[i]/(9**i)
  print(vec[i])
  
  
}

#Yes this series converges to zero as well

```


# arithmetic sequences

```{r}
n<- 20

vec <- c(1:n)
vec


for (i in vec ){
  
  vec[i] =  3 + (i - 1) * 3
  print(vec[i])
  
  #no this series diverges
  
  
}

```



```{r}
n<- 20

vec <- c(1:n)
vec


for (i in vec ){
  
  vec[i] =  3 * 2**(i-1)
  print(vec[i])
  
  
  #no this series diverges
  
}

```
---

# Sin Approximation


```{r}
n<- 20

vec <- c(1:n)
vec


for (i in vec ){
  
  vec[i] =  i - (i**3)/factorial(3) + (i**5)/factorial(5) + (i**7)/factorial(7)
  print(vec[i])
  
  #no this series diverges
  
  
}


```

---

#For loop with a matrix

```{r}
A <- matrix(1:20, nrow = 5, ncol = 4)
A


# empty matrix B
B <- matrix(NA, nrow = 5, ncol = 4)

# for loop to get matrix B
for (i in 1:nrow(A)) {
  for (j in 1:ncol(A)) {
    B[i,j] <- A[i,j] + i
  }
}

B

```

```{r}
set.seed(123)
X <- matrix(rnorm(12), nrow = 4, ncol = 3)
X


# empty matrix Y
Y <- matrix(NA, nrow = 4, ncol = 3)
Y


for (i in 1:nrow(X)) {
  for (j in 1:ncol(X)) {
    
    if (X[i,j] > 0 ){
    Y[i,j] <- (X[i,j]) ** .5 
    }
    
    if (X[i,j] < 0 ){
    Y[i,j] <- (X[i,j]) ** 2
    }
    
    
  }
  }
  


Y

```

---

# Dividing a number by 2 multiple times

```{r}
# your reduce() function

# This function will take in a number and divide it by 2 until it becomes off
reduce <- function(x) {
  
  while ((x %% 2) == 0) {
    
     x = x* .5
     print(x)
    
  }
  
  # Fill in.
  
}

reduce(898128000)


```
---

#Average

```{r}
x = c(1:100)


z = 0

for (i in x){
  
  z = z + i
}

z / length(x)



counter = 0
average = 0

while(counter < 1){
  
  average = sum(x)/length(x)
  counter = counter + 1

  
}

average

counter2 = 0
avg = 0

repeat {
  
  if (counter2 == 1) { # If val_rep is odd,
    break                  # end the loop.
  }
  avg = sum(x) / length(x)
  counter2 = counter2 + 1
  
}

avg


```

---

#Standard deviation

```{r}

sum = 0
x = c(1:100)

for (i in x){
  
  sum = sum + (i - mean(x))**2
}

sd = sqrt((1/(length(x)-1))*sum)
sd


#while loop
counter = 0

while (counter < 1){
  
  sd =  sqrt(sum((x-mean(x))^2/(length(x)-1)))
  counter = counter +1

}

sd

counter = counter - 1

repeat {
  
  if (counter ==1){
    break
  }
  
  sd =  sqrt(sum((x-mean(x))^2/(length(x)-1)))
  counter = counter +1
  
}

sd

```


---

#Geometric Mean

```{r}

sum = 1
x = c(1:100)

for(i in x){
  
  sum = sum * i}

geom_sum = sum**(1/length(x))

geom_sum


counter = 0

while (counter < 1){
  
  sum**(1/length(x))
  counter = counter + 1
}

counter = counter -1

repeat{
  
  if (counter == 1){
    break
  }
  
  geom_sum = sum ** (1/length(x))
  counter = counter + 1
  
}

geom_sum




```


---

#Distance Matrix of Letters

```{r}
# random distance matrix
num_letters <- length(LETTERS)
set.seed(123)
values <- sample.int(num_letters) 
distances <- values %*% t(values)
diag(distances) <- 0
dimnames(distances) <- list(LETTERS, LETTERS)

distances[1:5, 1:5]

#This function gets the distance from the matrix and returns the value associated with it
get_dist <- function(distance, ltrs){
  total = 0
  for (i in 1:(length(ltrs)-1)){ # 25
    if (!(ltrs[i] %in% LETTERS) & !(ltrs[i + 1] %in% LETTERS)) {
      stop("Unrecognized character")
    }
    total = total + distance[ltrs[i], ltrs[i+1]]
  }
  total
}


cal = c('C', 'A', 'L')
stats = c('S', 'T', 'A', 'T', 'S')
oski = c('O', 'S', 'K', 'I')
zzz = rep('Z', 3)
#lets = LETTERS
first = c('N', 'A','B')
last = c('K','I','Z')

# use your own 'first' and 'last' objects
strings <- list(
  cal = cal,
  stats = stats,
  oski = oski,
  zzz = zzz,
 # lets = 
  first = first,
  last = last
)

vec = rep(0, length(strings))

for (word in strings){
  
  print(get_dist(distances, word))
  vec[word] = get_dist(distances, word)
  
}

vec

#The strings_dist looks a little strange, with letters and the distances that correspond to them in a vector


```

